# Welcome to Jekyll!

title: Karl Vance
email: krvcrypto@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Coder, Bitcoin enthusiast, researcher. This is a github page for sharing things I find interesting on the topic of Bitcoin..
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://krvcrypto.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: krvcrypto
github_username:  krvcrypto

# Build settings
# theme: minima
theme: jekyll-theme-cayman

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

mathjax: true
